### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by 6--** [brandonsturgeon/warmane_armory_parser#1]
How can we use it?

**Comment by sarahsturgeon** [comment]
This project is very much in its infancy, but I believe it should be ~90% functional right now.

Right now, I'm just cloning this project, making a new `main.py` in the project root, and then doing something like this:
```py
from armory_parser import parse_character

print(parse_character("Moot"))
```

That'll output a massive json blob with most of the info we can parse from the armory.
